# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0002_auto_20181103_0812'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
